### ISSUE TITLE
example/turorial のコーディングルール統一とビルドイメージへの同梱・整理

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/chirimen-raspi3#21]
現在 @satakagi さんが頑張って Qiita から [Github 側のチュートリアル](https://github.com/chirimen-oh/tutorials/) に移転してコーディングルール変更も進めつつあるが、exaple (および jsbin/jsfiddle) のサンプル例はまだ async/await ではない Promise .then コードで書かれている。

また、tutorial が github repo に入ったら Qiita に接続せずとも見られるので全てオフラインでチュートリアルが可能となるから、tutorial もイメージに同梱してローカルのチュートリアルを表示する感じにするのが良いはず。

ざっくり想定タスクリスト:

- [ ] example のコード例 (https://github.com/chirimen-oh/chirimen-raspi3/tree/master/gc 配下)  とチュートリアルでコーディングルールの統一
  - [x] async/await
  - [x] #18 prettier などでのフォーマット統一 
- [ ] jsbin なども新しいコードのバージョンを用意して差し換え。
  - できればそこは自動化可能にしたいがそれはまた別の issue にて
    - #20 rpi3 ローカルで jsbin を動かすようにすると自動化も簡単そう
    - あるいは jsbin pro アカウントで write api 使って自動化するか、webdriver などで自動処理を書くか...
- [x] ビルドイメージに tutorial を同梱
  - [x] ビルドイメージのチュートリアルリンクを差し換え (オンライン版へのリンクも何処かに残す)
  - [x] 新しいチュートリアルの補足ページか何かにオリジナル Qiita へのリンクなどもしておく

**Comment by dynamis** [comment]
すべての example は修正しきれないので手の回る範囲でですが、以下の方針で書き換えを行っています
- HTML 要素の取得
  - いろいろな方法が使われているが getElementById に統一
    - window.elementId に対して elementId でいきなりアクセスする
    - getElementById
    - querySelector
- 実行タイミング
  - HTML 要素にアクセスできるためにいろいろな方法があるが、script defer に統一
    - script defer - これなら jsfiddle などのオンラインエディタが勝手に調整したりするロードタイミング制御とコンフリクトすることがないし、js コード中にその制御のコードを書く必要がなくてシンプル。説明としても HTML 読み込み後に実行するための属性だよ、の一言で済むので初心者に優しい
    - (window.)onload = function(){} - シンプルだけどあまり良くない古いコード
    - addEventListener("load") - 本当は DOMContentLoaded
    - addEventListener("load") - DOMContentLoaded とはなんぞやという説明が必要
- 関数名
  - mainFunction -> main

**Comment by kou029w** [comment]
https://github.com/chirimen-oh/chirimen-raspi3/issues/21#issuecomment-517090705 について #73 で対応完了

**Comment by kou029w** [comment]
JSBinについては #66 

- [ ] ところどころチュートリアルと異なり `val ^= 1` のようなコードが登場するので修正する
