### ISSUE TITLE
通電中に port.export("in") を呼ぶと Promise がいつまでも解決(拒否)しない

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/chirimen-raspi3#22]
await port.export("in") しようとして promise が resolve/reject されずに停止するケースがあった。

コードはタクトスイッチの example などで再現するが、物理配線側にタクトスイッチではなくロータリースイッチなど、手を離しても通電状態になる (なりうる) スイッチを利用した場合。タクトスイッチであれば押した状態、ロータリースイッチであれば通電するよう選択した状態でページをリロードすると port.export("in") の Promise が解決しない。

もし該当ピンが通電中は in に切り替えることがボードの仕様上不可能であれば Promise は reject すべき。

**Comment by tadfmac** [comment]
同根の可能性 https://github.com/chirimen-oh/chirimen-raspi3/issues/25

**Comment by satakagi** [comment]
確かに、同じバグと思えますね
