### ISSUE TITLE
GPIOのIN設定でsrv.jsが停止

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-raspi3#25]
ＧＰＩＯがPullUp状態になっていないときにINでGPIOを設定すると処理が破たんし停止してしまうらしいことが判明。結果として、何も配線しないと、4,5,6端子しかIN設定できない・・・

reset.shを動かすことで回復できるが、破たんするのは同じ

**Comment by sizuhiko** [comment]
`gpio` のnodeモジュールを違うものに変更してみると変わるかもしれないですが、やってみないとわからないですね...
`pigpio` とか `raspi-gpio` とか

**Comment by tadfmac** [comment]
https://github.com/EnotionZ/GpiO/blob/master/lib/gpio.js

の104行目

```.js
this.value = 0;
```

を
```.js
this.value = -1;
```

とかにすれば修正できます。

**Comment by satakagi** [comment]
追伸：
今現在最新のraspbianに @WhiteHawk-taka さん作の自動セットアップスクリプトを使ってセットアップした環境では、PUのポート(4,5,6)でも動作が停止してしまっていました。が、#38を適用することでこれも含め、すべてのポートの入力が動くようになりました。
