### ISSUE TITLE
setupの自動化

### ISSUE THREAD

**Issue by WhiteHawk-taka** [chirimen-oh/chirimen-raspi3#31]
image セットアップの手順書をスクリプト化したものを生成する。

https://github.com/WhiteHawk-taka/chirimen-setup

**Comment by WhiteHawk-taka** [comment]
Chromiumがlocalhostのhttpsで動作することを確認済み。
センサーが正しく動作することを確認して、このリポジトリの構成に合わせてmergeする。

**Comment by satakagi** [comment]
Thanks!
