### ISSUE TITLE
release ディレクトリの gc.zip, _gc.zip などを不要なリリース手順を確立する

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-raspi3#35]
もしもgcと_gcディレクトリの内容と同じものがzipされているだけなのだとすると、リリースが面倒になるので削除してしまった方が良いと思っていますが、他に何か違いや目的があるようでしたら教えてください。

**Comment by satakagi** [comment]
同様にバージョンを記載しているファイルが複数個所にあるのも削除してしまってもいいと思いますが、理由が何かあれば教えてください。

**Comment by tadfmac** [comment]
setup.md を見ていただければわかりますが、オンラインからsetupする手順で zipファイルを使っています。また、version.txtが複数あるのは、前回のオミュニティミーティングでお話した通り、srv.jsと httpdのドキュメントルートが異なるためで、(現在はpolyfill側は未対応ですが)、それぞれのversionの整合性を確認可能にするためです。

**Comment by dynamis** [comment]
setup.md (setup.sh) ではダウンロードして展開しているだけなので、gc.zip, gc_zip 自体をリリースファイルとして配布するのでなければ zip がリポジトリは以下にある必要は無さそうに見えました。

単純にリポジトリ全体の zip をダウンロードしてそこから必要なディレクトリを展開すれば良い気がするのですがそれではまずいもしくは gc, _gc 単体の zip を配付する需要が想定されていましたでしょうか。
https://github.com/chirimen-oh/chirimen-raspi3/archive/master.zip


関連して確認すると、cdn ディレクトリも gc 配下のコピーであれば直接 gc 配下を参照させるでも問題はない気がしますが、ディレクトリを揃える以外に、リリース前のコミットが混ざらないようにするためとか意図があるのでしょうか？

もし gc 配下の者と同じで良いのであれば cdn ファイルは現在 mz4u.net にあるものなども全自動でこのリポジトリからホスティングできるように何かセットアップできれば、cdn ディレクトリもなくすことが出来て release ディレクトリとスクリプトを廃止できる可能性があるのではないかと思っての確認です。

**Comment by dynamis** [comment]
リリース検証手順として、リポジトリにコミットする前に zip を作って zip からリリース手順を実行して検証するという流れになっていたために zip を作るリリース手順だったとのこと。

github リポジトリからのインストール、リリース検証とローカルディレクトリからのインストール、リリース検証の両方が出来るようになっていれば (setup.sh にオプションでローカルディレクトリなりその zip からのインストールなりを指定可能にすれば) リポジトリコミット前のテストの繰り返しも可能かつリポジトリには同じ中身 (で維持されるか分からない) zip を残さずに済む。

また、github からのインストールにしても特定のリビジョンでのインストールをするためにはリリースタグを付けたアーカイブをダウンロードしてインストール出来れば良いわけで、リモートの場合でも setup.sh ではインストールする対象を指定可能であるべき。

以上踏まえて作業手順:

- [ ] setup.sh で release ディレクトリ配下ではなくリポジトリの zip からインストールするように
- [ ] setup.sh でローカルディレクトリ or ZIP からのインストールを可能に
- [ ] setup.sh で github のタグ指定で特定リリースのインストールを可能に (master は開発中で更新され続ける前提に出来るように)
- [ ] release ディレクトリ配下の zip ファイルを削除する

**Comment by dynamis** [comment]
バージョン指定などの機能まで作らなかったが netlify で自動ビルド＆それを setup.sh で読み込む形にしたのでクローズ
