### ISSUE TITLE
テストスイート用のコードを追加する

### ISSUE THREAD

**Issue by saxAllan** [chirimen-oh/chirimen-raspi3#42]
リリーステストキット用のレポジトリコードを追加する

- [x] コードをリポジトリに入れる
- [ ] JS Binにも同じものを用意する (ついでに不足している他のものも)
  - [x] pirsensor
  - [x] multiBlinkAll
  - [x] buttonAll
  - [x] gp2y0e03
  - [x] veml6070
  - [x] multi-sensors
  - [x] arduino-steppingmotor
- [x] JS Binへのリダイレクトリンクを用意する https://github.com/chirimen-oh/r.chirimen.org/blob/master/public/_redirects
- [ ] multiBlinkAll のコードを整理する (テスト用ではないボタンの削除)
- [x] buttonAll は Pull Up テストは押したときに点くのではなく押したときに消えるものであることを明記

**Comment by dynamis** [comment]
こちらとリンク先にコードが入ってる。
https://github.com/chirimen-oh/chirimen-raspi3/tree/master/gc/testSet

jsbin の用意も完了している。更新は出来てないけどこの issue としてはクローズ
