### ISSUE TITLE
2018/10版をリリースする

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-raspi3#45]
# リリース作業時のチェックリストです
## githubリポジトリでのチェック
- [x] release.shを実行し、zipファイルが更新されていること
## SDイメージが正しく動くこと
- [x] zip化されたSDイメージの解凍
- [x] SDイメージのSDへの焼きこみ
- [x] 焼きこんだSDイメージの正常起動
- [x] パーティションの自動拡張

## コンテンツ・外部リンクに誤りがないこと
- [x] デスクトップ壁紙左下の日時が更新されていること
- [x] ブックマークのリンクが正しくアクセスできること
  - [x] Local Contents
  - [x] Examples/JSBin (via r.chirimen.org)
  - [x] tutorials/github (rawgit)
- [x] Topコンテンツ
- [x] Examplesインデックスコンテンツ(全てのExamplesへの正しくアクセスできるリンクがあること)
 - [x] 回路図もしくは解説ページ
 - [x] Local Examples
 - [x] jsBin (via w.chirimen.org)

## Local Examplesが正しく動くこと
- [x] GPIO 
  - [x] Partial Test Pass : GPIO-Blink及びGPIO-Button
  - [x] Full Test Pass : 全てのExamplesが動作すること
- [x] I2C
  - [x] Partial Test Pass : I2C-ADT7410を含む少なくとも二つ以上のExamplesが動作すること
  - [x] Full Test Pass : I2C-canzasi-blink及びI2C-arduino-steppingMotorを除く全てのExamplesが動作すること 
- [x] もしくは localhost://testSet/testAll.html　を　フルテスト専用ボード(@webDINO)を用いてテスト

**Comment by dynamis** [comment]
10 月になったので 2018/10 月版としてリリースする。具体的には 10/4 (木) の作業で計画中

**Comment by dynamis** [comment]
以下の点が少し気になりますが、ひとまずは

- 初回起動時に raspbian update したよという notice が表示される
- chromium 初回起動時にタブを復元したよと言う notice が表示される (以前もしていたと思う。ダメじゃないけど気持ち悪いので何故か要調査)
- h264ify (chromium アドオン) が無効化されてるから再度権限付与して有効化してねって表示される。Chrome のアップデートでもされてバージョン互換でも生じたのだろうか？それとも初回は出るものなのか？

以下は些末な問題と残りの todo な感じですが、ひとまず一式の動作として致命的な問題はないと検証されたのでリリース版とさせて頂ければ:
- jsbin リンク先がまだ用意できていないものはこれから用意する (ビルドにはリダイレクト URL のブックマークが入っているためビルド側は変更不要)
  - rawgit のままのページ達: https://github.com/chirimen-oh/r.chirimen.org/blob/master/public/_redirects
-  壁紙のビルド日付が 9.14 だけど今日は 10.5
  - まぁ。。。いいか。。。動作上の害はないし、9/14 時点の中身でブックマークとかが変わった程度という意味合いでご容赦を。。。

なお、チュートリアルはオンラインにしかないビルドなので実際使う人が現れるまでの間にいつでも更新可能なので、そちらに問題が見つかってもリリースとしては影響ありません。

**Comment by dynamis** [comment]
ブックマークミスがあったバージョン: https://download.chirimen.org/release/raspberry_pi_3/CHIRIMEN_Raspberry_pi_3_20181004RC1.zip

それを修正したバージョン:
https://download.chirimen.org/release/raspberry_pi_3/CHIRIMEN_Raspberry_pi_3_20181005.zip

こちらにて一旦リリースと言うことでクローズさせてください。

**Comment by dynamis** [comment]
おっと、イメージを公開する以外にタグを付けるとか色々やることがまだある気がするので reopen

**Comment by dynamis** [comment]
- [ ] リリースしたコミットにタグを付ける
- [ ] changelog ファイルを用意して書き込む

**Comment by satakagi** [comment]
jsbinリンク先、準備できてないのはkanzashi,stepping motor, 人感センサぐらいですかね?

**Comment by satakagi** [comment]
あ、操作ミス再オープンします。
