### ISSUE TITLE
ディスプレイ解像度設定のコードで Pi-Top のディスプレイを認識しなくなる

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/chirimen-raspi3#51]
現在下記のように /boot/config.txt を書き換えている結果 https://pi-top.com/ のディスプレイを認識しない。

https://github.com/chirimen-oh/chirimen-raspi3/blob/master/setup.sh#L39
```
# ディスプレイ解像度設定
echo -e 'hdmi_force_hotplug=1\nhdmi_group=2\nhdmi_mode=85\nhdmi_drive=2\n' | sudo tee -a /boot/config.txt
```

認識しないディスプレイができてしまうくらいなら解像度設定はしない方が良いと思うが、ディスプレイに応じて解像度の変更などをちゃんと書くならそれもありかも知れない。さて。

**Comment by WhiteHawk-taka** [comment]
Raspbianはディスプレイをあまり自動で認識するようにはできていないので、この設定を削除しても認識しないディスプレイは多数存在するようです。
