### ISSUE TITLE
エディタの同梱

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/chirimen-raspi3#56]
以前別の意図 (OS の統一) でディタの同梱をという話 #9 がありましたが、やはり CHIRIMEN Raspi3 には jsbin などを使うだけでなくエディタの同梱が必要かと思います。

初学・トライ時にはそれでよいのですが、作品レベルのものを開発していく上では jsbin などオンラインだけでは完結しなかったり、オンラインエディタでは開発ツールでのデバッグがしにくかったり、最初に試すとき以外は何らかの理由でローカルファイルの編集をすることになります。

現状同梱されているエディタ (vim/emacs) は流石に初心者には辛いし JavaScript のコードの強調表示などもされておらず非常に Typo などが多く、初学者向けの環境としては問題があります。

Web 開発の標準ツールとしてはもう VS Code で決まりなのですが、Chromium と同時起動するにはかなり重たいエディタになるため、gedit, Kate, Pluma, Geany あたりで何か入れておいた方が良さそうです。

まだちゃんと使って比較したことがないので具体的にどれがベストかは未検証です。VS Code も入れておいても良いと思いますが、重すぎるのでもっと軽量で ES 2017 (async/await) に対応したコード強調ができるものというのが要件かと思います。

ref: https://blog.codecamp.jp/linux-edit-12

**Comment by sizuhiko** [comment]
オンラインのVS Codeという意味では
https://stackblitz.com/
も有力だとは思いますが、ローカルではないですね...

**Comment by satakagi** [comment]
VS Code入れてどれぐらい重くなるか試してみましょうかね

**Comment by dynamis** [comment]
vs code 入れたい勢の声が強いので、入れるならついでに以下も

- [ ] vs code 本体
- [ ] vs code の eslint prettier プラグイン
- [ ] eslint を global install
- [ ] prettier を global install

**Comment by dynamis** [comment]
ローカルエディタとしては vscode (code-oss) が入ったのでこちらはクローズ
https://github.com/chirimen-oh/chirimen-raspi3/blob/master/setup.sh#L44

stackblitz や makecode 的な方向としては stackblitz はさっと react ではない raw/static な html/js を編集するワークスペースが作れなさそうだったが codesandbox は出来るのでそちらにて

ローカル vscode にプラグイン類については入れてないけど example ベースの編集などは codesandbox オンラインエディタが使えるようにすればローカルはユーザにお任せとして忘れることが出来る (see #71)

see also:
- https://github.com/chirimen-oh/tutorials/issues/48
- https://github.com/chirimen-oh/chirimen-raspi3/issues/71

**Comment by WhiteHawk-taka** [comment]
@dynamis code-oss に拡張機能は入っています。
https://github.com/chirimen-oh/chirimen-raspi3/blob/master/setup.sh#L81
