### ISSUE TITLE
エラーrejectした後、コマンドキューが残り続けて動作しなくなる

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-raspi3#58]
https://github.com/chirimen-oh/chirimen-raspi3/blob/d7b33bcefbe16f76348f0ea751922593400b8462/_gc/srv/srv.js#L556

この行の前にprocessQueue = [];を入れれば良いのではないかと思います。
なお同じくrejectしている部分があり、ここでも同じ現象が起きそう。

**Comment by tadfmac** [comment]
ありがとうございます。本件は不具合なので、ご提案の方法で修正方向で良いと思います。
