### ISSUE TITLE
チュートリアルページをたどっていってもOSがインストールできない

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-raspi3#6]
https://qiita.com/tadfmac/items/82817476615fdc7394b3
からたどっていって OSインストールの情報
https://gist.github.com/tadfmac/527b31a463df0c9de8c30a598872344d
まではたどり着くもOSイメージのDLができない状態です

**Comment by satakagi** [comment]
wikiのTutorialのページに、インストール方法のチュートリアルのリンクと、SDイメージのDL先に関する注記を追加しました。

**Comment by tadfmac** [comment]
ありがとうございます！
https://gist.github.com/tadfmac/527b31a463df0c9de8c30a598872344d
の記載を最新のSDカードimageへのリンクに修正しました！
