### ISSUE TITLE
contrib ディレクトリの jsbin リンク切れ

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/chirimen-raspi3#60]
http://chirimen.org/chirimen-raspi3/gc/top/examples/ に contrib が増えているが jsbin ページの用意とリンクができていないものがある。local リンクに書いてあるものと同じでよいので用意・追加・リンク設定 https://github.com/chirimen-oh/r.chirimen.org/blob/master/_redirects する

**Comment by dynamis** [comment]
- [ ] [contrib の example](https://github.com/chirimen-oh/chirimen-raspi3/tree/master/gc/contrib/examples) を jsbin に用意する
- [ ] リダイレクト URL 設定をする https://github.com/chirimen-oh/r.chirimen.org/blob/master/_redirects 
- [ ] example ページから r.chirimen.org URL へリンクさせる https://github.com/chirimen-oh/chirimen-raspi3/blob/master/gc/top/examples/index.html

**Comment by saxAllan** [comment]
Advanced まで含めて JSBin を用意しました。
