### ISSUE TITLE
_gc/unsupported ディレクトリは使われていないため消す

### ISSUE THREAD

**Issue by kou029w** [chirimen-oh/chirimen-raspi3#69]
_gc/unsupported ディレクトリが存在するが、今は使っていないため消して良いと考える

**Comment by dynamis** [comment]
github に残っている全く出番がなかったので基本的には不要ですが、サポートできないデバイスであることを何処かに分かりやすく記録はしておきたいですね。

https://github.com/chirimen-oh/chirimen-raspi3/wiki/Devices
とかにメモして消す前のリビジョンへのリンクをして削除で良さそうに思います。

**Comment by kou029w** [comment]
unsupported にある 超音波センサー SRF02 について https://github.com/chirimen-oh/chirimen-raspi3/wiki/Devices#chirimen-for-raspberry-pi-3-%E3%81%A7%E5%88%A9%E7%94%A8%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E3%83%87%E3%83%90%E3%82%A4%E3%82%B9 に記載しました
