### ISSUE TITLE
RasPi3上からリンクにアクセスできない

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/chirimen-raspi3#79]
https://tutorial.chirimen.org/raspi3/hellorealworld 内の

詳しく説明している **`チュートリアル`** を読みつつコードを書き換えてみたり、各デバイス用の回路図、サンプルコード、オンライン版を用意している Example 集ページ を参考に、色々なデバイスを繋いで自由なアイデアを形にしてみてください。

「チュートリアル」のリンク　https://tutorial.chirimen.org/raspi3/ が chroniumからだと
「このサイトにアクセスできません」と表示される

**PCからだと問題なし**

**Comment by kou029w** [comment]
なぜでしょうねぇ…?
リンク切れでなければ、回線の問題かあるいは時計が合ってないことによってSSL証明書の検証に失敗しているとかでしょうか

**Comment by gurezo** [comment]
貸し出し機材とイメージをその場で焼いた奴どちらも同じ症状でした。。。
PCが問題ないですね。。。

**Comment by gurezo** [comment]
回線の問題でした。
コワーキングスペースのwi-fiだと何故かアクセスができなかったのですが、
手持ちのモバイルwi-fiだと見れました。

解せないのは、問題になったページだけ何故か見れなかったという点です。
それ以外のページはなんの問題もなく閲覧できていました。。。

**Comment by gurezo** [comment]
サイトの問題でないようなので、クローズします。
同様の現象が再発した時にまたオープンしたいと思います。
