### ISSUE TITLE
イベント用にテキストエディタ入りのイメージが必要

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/chirimen-raspi3#9]
### subject
イベントなどで、Raspbianに別途テキストエディタ（標準以外）を入れた
イメージを用意したほうが良い。
※ [はじめての JavaScript 1DAY 講習会 ](https://connpass.com/event/72869/)からのフィードバック
  WindowsとmacOSとで、Javascriptの実習で、フォローが必要だった為

### 候補
- atom
- sublimetext
- vscode
-  any

### TODO
- エディタの選定
- イメージの作成
- 配布物の変更（ダウンロードファイル）

**Comment by tadfmac** [comment]
CHIRIMEN for Raspiでは基本的に、jsfiddleとかjsbinを使う方針なんですが、それではだめですか?

**Comment by gurezo** [comment]
@tadfmac issue を立てる場所を間違えたようです。
> ※ [はじめての JavaScript 1DAY 講習会 ](https://connpass.com/event/72869/)からのフィードバック
>   WindowsとmacOSとで、Javascriptの実習で、フォローが必要だった為
Javascriptの実習をやるPCが、WindowsとmacOSとで、異なるサポートが必要だったのが問題でした。
Javascriptの実習をPC行う際にどちらかのOSに統一しましょうというのが、命題でした。

**Comment by gurezo** [comment]
issue 違いなので、closeします。
